name: Run Cucumber and PetStore Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: "run-api-tests-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Cucumber tests
        run: mvn test -Dtest=BDD_example.Runner

      - name: Run PetStoreTest
        run: mvn test -Dtest=tests.PetStoreTest

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cucumber-reports/

      - name: Post GitHub Pages link
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github, context } = require('@actions/github');
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const issue_number = context.payload.pull_request ? context.payload.pull_request.number : context.runId;
            const url = `https://github.com/${owner}/${repo}/blob/gh-pages/cucumber.xml`;
            const comment = `The XML report is available [here](${url}).`;
            await github.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment
            });